# Generated by Django 3.1.4 on 2020-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20201228_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='order_date',
            field=models.DateField(),
        ),
    ]
