# Generated by Django 3.1.4 on 2020-12-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20201228_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='order_date',
        ),
    ]
